### PR TITLE
Address book to functional calgo

### LINKED ISSUE #10: find command (showing nutritional composition): As a person who does not know what my food is made of, I want to go and find out the nutritional composition of a particular food.

### LINKED ISSUE #43: Data Search & Storage - Remodel AB3 to suit the Calgo Project, Create Calorie, Carbohydrate, Protein, Fat objects, Change Storage functionalities to allow storage of new data, Change storage json file, ensure the following methods work: find (by Food item/substring full word), list (every Food in Food Record), both commands giving results with all nutritional information.

### LINKED ISSUE #55: list command (with all relevant information): As user who dislikes memorising things, I want to have a way to know what Food items have their data currently in the records.

### LINKED ISSUE #56: find command: As a user who dislikes sieving through information and prefers to have only the relevant information presented, I want to have a way to easily find specific Food items in the records with their relevant information.

### LINKED ISSUE #90: Storage for Nutritional Composition: As a health-conscious person, I want to store the nutritional information about my food so I can easily refer to them next time.

### PR DESCRIPTION
**Pull request by eugenetyc**
With this update,
- GUI shows nutritional information as "Type: Value"
- Tagging is now enabled
- Multiple Tags are allowed

Much thanks @jeremylow97 @jeremylow97 @ray-97 @J-Dan23 for the help.
Cheers!

### CODE REVIEW

**Comment by J-Dan23** [comment]
Looking great man, thanks for the work.

**Review by J-Dan23 — COMMENTED** [review]
GUI looks fine, shouldn't conflict with my changes.

**Comment by ray-97** [comment]
Looks good, please merge!

**Comment by thrivinb** [comment]
LGTM! Keep up the great work.

**Comment by jeremylow97** [comment]
Looks really good! Good job

**Pull request merged**
